update for 2010.1

diff --git a/make_release b/make_release
--- a/make_release
+++ b/make_release
@@ -2,10 +2,11 @@
 
 RELEASE_DIR=/home/bbb/releases
 
-LIBLITMUS_DIR=/home/bbb/dev/liblitmus2008
-LITMUS_DIR=/home/bbb/dev/litmus2008
+LIBLITMUS_DIR=/home/bbb/dev/liblitmus2010
+LITMUS_DIR=/home/bbb/dev/litmus2010
+FT_TOOLS_DIR=/home/bbb/ft_tools/
 
-BASE_TAG="v2.6.24"
+BASE_TAG="v2.6.32"
 
 TAG=$1
 
@@ -40,10 +41,17 @@ function release_liblitmus {
     return 0
 }
 
+function release_ft_tools {
+    echo "Releasing ft_tools."
+    cd $FT_TOOLS_DIR || die "Could not cd to $FT_TOOLS_DIR."
+    archive ft_tools $TARGET/ft_tools-$TAG.tgz || die "Could not build archive."
+    return 0
+}
+
 function release_litmus {
     echo "Releasing LITMUS^RT."
     cd $LITMUS_DIR || die "Could not cd to $LITMUS_DIR."
-    git-diff -p --stat $BASE_TAG $TAG > $TARGET/litmus-rt-$TAG.patch || \
+    git diff -p --stat $BASE_TAG $TAG > $TARGET/litmus-rt-$TAG.patch || \
 	die "Could not create patch."
     return 0
 }
@@ -57,6 +65,7 @@ mkdir -p $TARGET    || die "Could not make directory $TARGET."
 
 release_litmus      || die "Releasing LITMUS^RT failed."
 release_liblitmus   || die "Releasing liblitmus failed."
+release_ft_tools    || die "Releasing ft_tools  failed." 
 
 cd $TARGET
 echo "Generating check sums." 
